services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "${PORT}:8081"
    volumes:
      - ${DATAPATH}:/downloads
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
